lifecycle_manager:
  ros__parameters:
    autostart: false          # <- was true
    node_names: ["map_server", "amcl"]


amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan
    min_particle_limit: 500
    max_particle_limit: 2000

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /path/to/your_map.yaml
    frame_id: map


# fork_navigation/config/navigation.yaml
bt_navigator:
  ros__parameters:
    use_sim_time: true

    # Tell the navigator which BT files to load
    default_nav_to_pose_bt_xml:      "/home/fork/fork_ws/install/fork_navigation/share/fork_navigation/behavior_trees/nav_to_pose_stable.xml"




planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0

    # The default behavior tree expects a plugin name "GridBased"
    planner_plugins: ["GridBased"]

    # But here we point "GridBased" at the SmacPlannerHybrid plugin
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      # --- key narrow-corridor fixes ---
      minimum_turning_radius: 1.36 # 0.75     # <— try 0.5–0.9 until it works
      max_iterations:        -1        # unlimited
      max_planning_time:      8.0      # seconds
      allow_unknown:          true
      downsample_costmap:     false
      downsampling_factor:    1
      angle_quantization_bins: 48
      tolerance:              0.35     # little bit of slack

      # --- NEW: let the search use reverse freely ---
      reverse_penalty:        1.0    # ▶ 1.0 = no extra cost (default is 2.1)
      change_penalty:         0.0    # cost for switching between fwd / rev
      non_straight_penalty:   1.0    # don’t discourage curves
      cost_penalization_weight: 1.0  # don’t blow up costs just for reversing
      
      angle_quantization_bins: 48
      motion_model_for_search: "REEDS_SHEPP"





behavior_server:
  ros__parameters:
    use_sim_time: true

    spin_time_allowance: 10.0







controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      desired_linear_vel:       0.50
      min_linear_vel:           0.10
      max_linear_accel:         0.25

      max_angular_vel:          0.30  
      max_angular_accel:        0.30

      lookahead_dist: 1.4 # lookahead_dist ≈ 1.0 – 1.4 × wheel_base ≈ 1.4 – 1.9 m
      use_velocity_scaled_lookahead_dist: false
      # (If you later re‑enable velocity scaling, set:
      #   lookahead_time: 3.0
      #   min_lookahead_dist: 1.36
      #   max_lookahead_dist: 2.70)
      

      # disable rotation-to-heading so we can reverse
      use_rotate_to_heading:     false
      rotate_to_heading_angular_vel: 0.30
      rotate_to_heading_min_angle:   0.785

      # <<<<<<<<< ENABLE BACKING UP <<<<<<<<<
      allow_reversing:           true

      # ─── SLOW-DOWN WINDOW ────────────────────────────────────────────
      approach_velocity_scaling_dist: 1.20   # start braking 1.2 m before goal  ▼

      inflation_scale:           3.0
      use_regulated_linear_velocity_scaling:     true
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist:         0.60
      cost_scaling_gain:         1.00
      regulated_linear_scaling_min_radius: 1.20
      min_approach_linear_velocity:       0.02


      use_forward_point_offset: true
      forward_point_offset: 0.8   # smaller than wheel bas
      curvature_lookahead_dist:         1.0
      min_distance_to_obstacle:         0.6       # must be ≤ look‑ahead






# --- Global Costmap ---
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      footprint: "[[-0.2, -0.3], [-0.2, 0.7], [1.66, 0.7], [1.66, -0.3]]"
      #footprint_padding: 0.10
      robot_base_frame: base_link
      resolution: 0.05
      size_x: 50
      size_y: 50
      origin_x: 0.0
      origin_y: 0.0
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          obstacle_max_range: 10.5
          obstacle_min_range: 0.1
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6       # Distance around obstacles to inflate costs
        cost_scaling_factor: 10.0    # How quickly cost drops off with distance from obstacle
        lethal_radius: 0.2          # Radius at which a cell is considered totally blocked





# --- Local Costmap ---
local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 12
      height: 12
      resolution: 0.03
      footprint: "[[-0.2, -0.3], [-0.2, 0.7], [1.66, 0.7], [1.66, -0.3]]"
      #footprint_padding: 0.10
      robot_base_frame: base_link
      plugins: ["obstacle_layer", "inflation_layer"]
      
      update_frequency: 10.0    # More frequent updates for real-time obstacle avoidance
      publish_frequency: 5.0

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observatio      tolerance: 0.2
      motion_model_for_search: "REEDS_SHEPP"
      angle_quantization_bins: 72
      minimum_turning_radius: 1.36  # matching your wheelbasen_sources: scan
      scan:
        topic: /scan
        obstacle_max_range: 10.5
        obstacle_min_range: 0.1
        raytrace_max_range: 20.0
        raytrace_min_range: 0.0
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6    
        cost_scaling_factor: 10.0